scene_id: "sacha_kitchen"

conceptgraphs_dir: "./datasets"
scene_dir: "${paths.conceptgraphs_dir}/${paths.scene_id}"

out_subdir: "sacha_kitchen"
out_dir: "./sampled_scenes"
out_scene_dir: "${paths.out_dir}/${paths.out_subdir}/${paths.scene_id}/generated_on_${now:%Y-%m-%d-%H-%M-%S}"
